using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Cromwell.SourceGenerator;

[Generator]
public class ViewLocatorGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
           .CreateSyntaxProvider(
                static (node, _) => node is AttributeSyntax attribute && attribute.Name.ToString() == "ViewPair",
                static (context, _) => (AttributeSyntax)context.Node)
           .Collect();

        var combined = context.CompilationProvider.Combine(provider);

        context.RegisterSourceOutput(combined, (spc, pair) =>
        {
            var (compilation, list) = pair;

            if (list.Length == 0)
            {
                return;
            }

            var stringBuilder = new StringBuilder();
            stringBuilder.AppendLine("// <auto-generated />");
            stringBuilder.AppendLine();
            stringBuilder.AppendLine("#nullable enable");
            stringBuilder.AppendLine();
            stringBuilder.AppendLine("namespace Cromwell.SourceGenerator;");
            stringBuilder.AppendLine();
            stringBuilder.AppendLine($"public class CromwellViewLocator : global::{TypeNames.IDataTemplate}");
            stringBuilder.AppendLine("{");
            stringBuilder.AppendLine($"    public global::{TypeNames.Control}? Build(object? param)");
            stringBuilder.AppendLine("    {");
            stringBuilder.AppendLine("        if (param is null)");
            stringBuilder.AppendLine("        {");
            stringBuilder.AppendLine("            return null;");
            stringBuilder.AppendLine("        }");

            foreach (var source in list)
            {
                var viewType = source.GetAttributeValueType(0);
                var viewModelType = source.GetAttributeValueType(1);
                stringBuilder.AppendLine($"        if (param is global::{viewModelType.GetFullName(compilation)})");
                stringBuilder.AppendLine("        {");
                stringBuilder.AppendLine($"            return new global::{viewType.GetFullName(compilation)}();");
                stringBuilder.AppendLine("        }");
            }

            stringBuilder.AppendLine();

            stringBuilder.AppendLine(
                $"        return new global::{TypeNames.TextBlock} {{ Text = \"Not Found: \" + param.GetType().ToString(), }};");

            stringBuilder.AppendLine("    }");
            stringBuilder.AppendLine();
            CreateMatchMethod(stringBuilder);
            stringBuilder.AppendLine("}");
            var text = stringBuilder.ToString();
            spc.AddSource("ViewLocator.g.cs", SourceText.From(text, Encoding.UTF8));
        });
    }

    private void CreateMatchMethod(StringBuilder stringBuilder)
    {
        stringBuilder.AppendLine(
            $"    public bool Match(object? data) => data is global::{TypeNames.ObservableObject};");
    }
}